services:
  db:
    image: mysql:8
    restart: always

    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 1g

    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${WORDPRESS_DB_NAME}
      - MYSQL_USER=${WORDPRESS_DB_USER}
      - MYSQL_PASSWORD=${WORDPRESS_DB_PASSWORD}

    volumes:
      - ./app/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 512m

    ports:
      - 3001:80

    environment:
      - PMA_HOST=db

    depends_on:
      - db

  wordpress:
    image: wordpress:${WORDPRESS_IMAGE_TAG}
    restart: unless-stopped

    deploy:
      resources:
        limits:
          cpus: "0.30"
          memory: 512m

    ports:
      - ${WORDPRESS_HTTP_PORT}:80

    volumes:
      - ./app/wordpress:/var/www/html

    depends_on:
      - db
